const strings = {
  searchPattern: "Search for patterns",
  pressFocus: "Press '/' to focus",
  title: "SVG Pattern Generator",
  heading: "Customizable SVG patterns for your projects",
  keywords: "svg patterns, patterns, svg backgrounds, vector wallpaper, pattern generator, pattern maker",
  patterns: "patterns",
  license: "MIT License",
  free: "Free",
  description:
    "A simple online pattern generator to create repeatable SVG patterns. Speed up your website without compromising on image quality. Perfect for website backgrounds, apparel, branding, packaging design and more.",
  filter: "Filter",
  sort: "Sort",
  filterMode: "Filter by Mode",
  filterColors: "Filter by Colors",
  allModes: "All modes",
  stroke: "Stroke",
  fill: "Fill",
  allColors: "All colors",
  colors: "colors",
  stroke: "Stroke",
  latest: "Latest",
  oldest: "Oldest",
  alphabetical: "Alphabetical",
  updateDate: "Updated Date",
  changeTheme: "Change Theme",
  changelog: "Changelog",
  features: "Features",
  privacy: "Privacy Policy",
  privacyFull: "This app does not collect or store any user data",
  signUp: "Sign up for project updates and get free patterns delivered monthly to your inbox",
  email: "Your email address",
  sendPatterns: "Send me the patterns",
  zoom: "Zoom",
  hSpacing: "Horizontal Spacing",
  vSpacing: "Vertical Spacing",
  angle: "Angle",
  inspire: "Inspire Me",
  random: "Random Pattern",
  reset: "Reset",
  copy: "Copy",
  copyCSS: "Copy CSS",
  copySVG: "Copy SVG",
  download: "Download",
  downloadSVG: "Download as SVG file",
  downloadPNG: "Download as PNG file",
  dimensions: "Dimensions",
  width: "Width",
  height: "Height",
  hide: "Hide UI",
  lock: "Lock",
  unlock: "Unlock",
  checkOut: "If you love creating SVG patterns and backgrounds, you should check this out.",
  generate: "Generate fully customizable SVG patterns for free.",
  patternsCount: "140+ patterns available at https://pattern.monster",
  square: "Square",
  rounded: "Rounded",
  join: "Join Mode",
  tweet: "Share your tweet",
};

export default { strings };
