const strings = {
  searchPattern: "Search for patterns",
  pressFocus: "Press '/' to focus",
  title: "SVG Pattern Generator",
  heading: "Customizable SVG patterns for your projects",
  keywords: "svg patterns, patterns, svg backgrounds, vector wallpaper, pattern generator, pattern maker",
  patterns: "patterns",
  license: "MIT License",
  free: "Free",
  description:
    "A simple online pattern generator to create repeatable SVG patterns. Speed up your website without compromising on image quality. Perfect for website backgrounds, apparel, branding, packaging design and more.",
  filter: "Filter",
  sort: "Sort",
  filterMode: "Filter by Mode",
  filterColors: "Filter by Colors",
  allModes: "All modes",
  stroke: "Stroke",
  fill: "Fill",
  allColors: "All colors",
  colors: "colors",
  latest: "Latest",
  oldest: "Oldest",
  alphabetical: "Alphabetical",
  updateDate: "Updated Date",
  changeTheme: "Change Theme",
  changelog: "Changelog",
  features: "Features",
  privacy: "Privacy Policy",
  privacyFull: "This app does not collect or store any user data",
  signUp: "Sign up for project updates and get free patterns delivered monthly to your inbox",
  email: "Your email address",
  sendPatterns: "Send me the patterns",
  zoom: "Zoom",
  hSpacing: "Horizontal Spacing",
  vSpacing: "Vertical Spacing",
  angle: "Angle",
  inspire: "Inspire Me",
  random: "Random Pattern",
  reset: "Reset",
  copy: "Copy",
  copyCSS: "Copy CSS",
  copySVG: "Copy SVG",
  download: "Download",
  downloadSVG: "Download as SVG file",
  downloadPNG: "Download as PNG file",
  dimensions: "Dimensions",
  width: "Width",
  height: "Height",
  hide: "Hide UI",
  lock: "Lock",
  unlock: "Unlock",
  checkOut: "If you love creating SVG patterns and backgrounds, you should check this out.",
  generate: "Generate fully customizable SVG patterns for free.",
  patternsCount: "180+ patterns available at https://pattern.monster",
  square: "Square",
  rounded: "Rounded",
  join: "Join Mode",
  tweet: "Share your tweet",
  waves: "Waves",
  chevron: "Chevron",
  straightLines: "Straight Lines",
  crossSection: "Cross Section",
  brickWall: "Brick Wall",
  herringbone: "Herringbone",
  flower: "Flower",
  plus: "Plus",
  circles: "Circles",
  concentricCircles: "Concentric Circles",
  adjointedCircles: "Adjointed Circles",
  adjointedDiamonds: "Adjointed Diamonds",
  diamonds: "Diamonds",
  hexagon: "Hexagon",
  overlappingHexagons: "Overlapping Hexagons",
  squaresSquares: "Squares & Squares",
  squaresDiamonds: "Squares & Diamonds",
  squaresCircles: "Squares & Circles",
  squaresPlus: "Squares & Plus",
  squaresStars: "Squares & Stars",
  starsLines: "Stars & Lines",
  triangles: "Triangles",
  invertedTriangles: "Inverted Triangles",
  checkerboard: "Checkerboard",
  japanesePattern: "Japanese Pattern",
  eyes: "Eyes",
  jigsaw: "Jigsaw",
  railroad: "Railroad",
  octagons: "Octagons",
  lines: "Lines",
  scales: "Scales",
  leaves: "Leaves",
  pipes: "Pipes",
  zebra: "Zebra",
  memphis: "Memphis",
  greekKey: "Greek Key",
  chinese: "Chinese Pattern",
  newPattern: "New Pattern",
  doubleBubble: "Double Bubble",
  stars: "Stars",
  semicircles: "Semicircles",
  songket: "Songket Pattern",
};

export default { strings };
