const strings = {
  searchPattern: "Nach Mustern suchen",
  pressFocus: "Drücke '/' zum Fokussieren",
  title: "SVG Muster Generator",
  heading: "Anpassbare SVG Muster für Ihre Projekte",
  keywords: "svg muster, muster, svg hintergründe, vektor hintergrund, muster generator, muster erstellung",
  patterns: "Muster",
  license: "MIT Lizenz",
  free: "Kostenlos",
  description: "Ein einfacher Online-Mustergenerator um wiederholbare SVG-Muster zu erstellen. Beschleunige Deine Website ohne Kompromisse in der Bildqualität. Perfekt für Webseiten-Hintergründe, Bekleidung, Branding, Verpackungsdesign und vieles mehr.",
  filter: "Filter",
  sort: "Sortieren",
  filterMode: "Filtern nach Modus",
  filterColors: "Filtern nach Farben",
  allModes: "Alle Modi",
  stroke: "Strichstärke",
  fill: "Füllung",
  allColors: "Alle Farben",
  colors: "Farben",
  latest: "Neueste",
  oldest: "Älteste",
  alphabetical: "Alphabetisch",
  updateDate: "Aktualisierungsdatum",
  changeTheme: "Thema ändern",
  changelog: "Änderungsprotokoll",
  features: "Funktionen",
  privacy: "Datenschutzerklärung",
  privacyFull: "Diese App erfasst oder speichert keine Benutzerdaten",
  signUp: "Melde Dich für Projektupdates an und erhalte monatlich kostenlose Muster in Deinen Posteingang",
  email: "Deine E-Mail-Adresse",
  sendPatterns: "Schicke mir die Muster",
  zoom: "Vergrößerung",
  hSpacing: "Horizontaler Abstand",
  vSpacing: "Vertikaler Abstand",
  angle: "Winkel",
  inspire: "Inspiriere mich",
  random: "Zufälliges Muster",
  reset: "Zurücksetzen",
  copy: "Kopieren",
  copyCSS: "CSS kopieren",
  copySVG: "SVG kopieren",
  download: "Herunterladen",
  downloadSVG: "Als SVG-Datei herunterladen",
  downloadPNG: "Als PNG-Datei herunterladen",
  dimensions: "Größe",
  width: "Breite",
  height: "Höhe",
  hide: "UI ausblenden",
  lock: "Sperren",
  unlock: "Entsperren",
  checkOut: "Wenn Du gerne SVG-Muster und -Hintergründe erstellst, sollten Du dir das ansehen.",
  generate: "Generiere vollständig anpassbare SVG Muster, kostenlos.",
  patternsCount: "140+ Muster auf https://pattern.monster verfügbar",
  square: "Quadrat",
  rounded: "Gerundet",
  join: "Verbinden Modus",
  tweet: "Tweet teilen",
  waves: "Wellen",
  chevron: "Zickzack",
  straightLines: "Gerade Linien",
  crossSection: "Schnittbild",
  brickWall: "Ziegelmauer",
  herringbone: "Fischgräte",
  flower: "Blume",
  plus: "Plus",
  circles: "Kreise",
  concentricCircles: "Konzentrische Kreise",
  adjointedCircles: "Verbundene Kreise",
  adjointedDiamonds: "Verbundene Diamanten",
  diamonds: "Diamanten",
  hexagon: "Sechseck",
  overlappingHexagons: "Überlappende Sechsecke",
  squaresSquares: "Quadrate & Quadrate",
  squaresDiamonds: "Quadrate & Diamanten",
  squaresCircles: "Quadrate & Kreise",
  squaresPlus: "Quadrate & Plus",
  squaresStars: "Quadrate & Sterne",
  starsLines: "Sterne & Linien",
  triangles: "Dreiecke",
  invertedTriangles: "Invertierte Dreiecke",
  checkerboard: "Schachbrett",
  japanesePattern: "Japanisches Muster",
  eyes: "Augen",
  jigsaw: "Puzzle",
  railroad: "Eisenbahn",
  octagons: "Achteck",
  lines: "Linien",
  scales: "Schindeln",
  leaves: "Blätter",
  pipes: "Rohre",
  zebra: "Zebra",
  memphis: "Memphis",
  greekKey: "Meander",
  chinese: "Chinesisches Muster",
  newPattern: "Neues Muster",
  doubleBubble: "Doppel-Blase",
  stars: "Sterne",
  semicircles: "Halbkreise",
  songket: "Songket Muster",
    };

export default { strings };
